### PR TITLE
Adding Support to AllstarRo client

### PR DESCRIPTION
**Pull request by noxnoire**
just adding  support for allstar ro , the hp & name address

### CODE REVIEW

**Comment by markiing** [comment]
Hey @noxnoire . Thanks for that.

Question:

There's two address for same `name` property.

``` {
        "name": "AllstarRO",
        "description": "AllstarRO_Alt",
        "hpAddress": "0x10DCE10",
        "nameAddress": "0x10DF5D8"
    }
```

`AllstarRO_Alt` is another client?

**Comment by noxnoire** [comment]
no , its the same client , but both adress seemed to be working across client restarts

**Comment by markiing** [comment]
If we have same address for same `name` property, the first one ever will be choosed.

`AllstarRO_Alt` never will be picked by 4R in this case.

Is really necessary?

https://github.com/4RTools/4RTools/blob/main/Model/Hexed.cs#L194

**Comment by noxnoire** [comment]
actually no , i just forgot that only checks for hp addr

**Comment by markiing** [comment]
Okay.

Make the changes and will be merged.

Thanks again 🎉

**Comment by afonsocdaniel** [comment]
Thanks for the contribution @noxnoire !

**Pull request merged**
